version: '3.8'

services: 
    postgres: 
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD=123
        ports: 
            - '5432:5432'
        volumes: 
            - ./database:/var/lib/postgresql/data
    server: 
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        ports: 
                - '3000:3000'
        restart: on-failure
        volumes: 
            - /app/node_modules
            - ./server:/app
        
        environment: 
            - EXPRESSPORT=3000
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=123
            - PGPORT=5432
            - NODE_ENV=development

        links: 
            - postgres
        depends_on: 
            - postgres